org: soareseds
app: aws-python-project
service: aws-python-proj

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    vpc:
      securityGroupIds:
        - sg-0650bea1295b0aac9
      subnetIds:
        - subnet-0ee9704c274972d9b
	
    events:
      - http:
          path: hello
          method: get
